"""
Contacts Outreach Tracker -- a separate, small, APPEND-ONLY file: just the
named contacts research has actually found (not every researched company --
if 100 companies are researched and only 1 has a named contact, this file
has exactly 1 row), so Faheem can work through outreach at his own pace
without the big raw results file in the way.

APPEND-ONLY BY DESIGN
---------------------
Every time Account_research_automation.py's run() finishes, this file gets
updated -- but only ADDS newly-found (Company, Name) pairs it hasn't seen
before. Existing rows, and whatever Faheem has already marked in the
Reached Out / Response columns, are read back in and preserved untouched.
Nothing here ever deletes a row. This is deliberate: the "did we already
show this bug" mistake to avoid is Alex's site losing data on every
refresh -- this file is designed so that can't happen even by accident.

Dedup key is (Company, Name), not Company alone -- if the same company
later shows a DIFFERENT named contact (role changed, new hire), that's a
new real finding worth its own row, not a value to silently overwrite.

CHECKBOXES
----------
Real clickable Excel checkboxes (ActiveX/form controls) don't survive
being regenerated by a script well and are painful to produce via openpyxl.
Used Data Validation dropdowns instead (Yes/No, blank = not yet
determined) -- click the cell, pick from the dropdown, same result with
none of the fragility.
"""

from pathlib import Path

import pandas as pd
from openpyxl.worksheet.datavalidation import DataValidation

import xlsx_style

CONTACTS_TRACKER_XLSX = "Contacts_Outreach_Tracker.xlsx"

COLUMNS = ["Company", "Name", "Role/Title", "Contact LinkedIn URL", "Date Found", "Reached Out", "Response"]


def _load_existing(path=CONTACTS_TRACKER_XLSX):
    if not Path(path).exists():
        return pd.DataFrame(columns=COLUMNS)
    df = pd.read_excel(path)
    df.columns = [str(c).strip() for c in df.columns]
    for col in COLUMNS:
        if col not in df.columns:
            df[col] = ""
    return df[COLUMNS]


def update_tracker(results, path=CONTACTS_TRACKER_XLSX):
    """results: list of AccountResult (or anything with .company,
    .named_contact, .contact_title, .contact_linkedin_url attributes) from
    a just-finished research run. Returns the number of NEW rows added."""
    existing = _load_existing(path)
    existing_keys = set(zip(existing["Company"].astype(str), existing["Name"].astype(str)))

    today = pd.Timestamp.now().date().isoformat()
    new_rows = []
    for r in results:
        name = (r.named_contact or "").strip()
        if not name:
            continue  # this is the whole point -- only rows with an actual name found
        key = (str(r.company), name)
        if key in existing_keys:
            continue
        new_rows.append({
            "Company": r.company,
            "Name": name,
            "Role/Title": r.contact_title or "",
            "Contact LinkedIn URL": r.contact_linkedin_url or "",
            "Date Found": today,
            "Reached Out": "",
            "Response": "",
        })
        existing_keys.add(key)  # guards against the same name appearing twice within one results batch too

    if not new_rows:
        if not existing.empty:
            _write(existing, path)  # still re-apply styling/dropdowns even if nothing new
        return 0

    combined = pd.concat([existing, pd.DataFrame(new_rows, columns=COLUMNS)], ignore_index=True)
    _write(combined, path)
    return len(new_rows)


def _write(df, path):
    df.to_excel(path, index=False)
    xlsx_style.style_xlsx(path)
    _apply_yes_no_dropdowns(path)


def _apply_yes_no_dropdowns(path):
    import openpyxl
    wb = openpyxl.load_workbook(path)
    ws = wb.active

    dv = DataValidation(type="list", formula1='"Yes,No"', allow_blank=True)
    ws.add_data_validation(dv)

    header = [c.value for c in ws[1]]
    for col_name in ("Reached Out", "Response"):
        if col_name not in header:
            continue
        col_idx = header.index(col_name) + 1
        col_letter = openpyxl.utils.get_column_letter(col_idx)
        # Cover plenty of rows beyond current data so future appended rows
        # (added by future runs) already carry the dropdown without needing
        # this function to guess the exact final row count.
        dv.add(f"{col_letter}2:{col_letter}5000")

    wb.save(path)
